apiVersion: v1
kind: Service
metadata:
  name: snake-service-test
  annotations:
    service.cloud.tencent.com/direct-access: "true"
  labels:
    stage: test
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  ports:
    - port: 8888
#      nodePort: 32000
      targetPort: 8888
      protocol: UDP
  selector:
    app: greedy-snake-test
#  sessionAffinityConfig:
#    clientIP:
#      timeoutSeconds: 3600
  #  externalIPs:
  #    - 42.192.43.222