apiVersion: v1
kind: Service
metadata:
  name: dgs-srv
  annotations:
    service.cloud.tencent.com/direct-access: "true"
#  labels:
#    stage: test
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
#  sessionAffinity: ClientIP
  ports:
    - port: 32001
      nodePort: 32001
      targetPort: 8888
      protocol: UDP
  #  externalIPs:
  #    - 42.192.43.222
  selector:
    app: dgs
#  sessionAffinity: ClientIP
#  sessionAffinityConfig:
#    clientIP:
#      timeoutSeconds: 3600