apiVersion: v1
kind: Service
metadata:
  name: snake-service
spec:
  type: NodePort
  ports:
    - port: 8888
      nodePort: 31000
      targetPort: 8888
      protocol: UDP
  #  externalIPs:
  #    - 42.192.43.222
  selector:
    app: greedy-snake-dev
    stage: dev
#  sessionAffinity: ClientIP
#  sessionAffinityConfig:
#    clientIP:
#      timeoutSeconds: 3600