// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: notify.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityInfoChangeNotify *EntityInfoChangeNotify `protobuf:"bytes,1,opt,name=entityInfoChangeNotify,proto3" json:"entityInfoChangeNotify,omitempty"` //实体的属性变化通知
	GameGlobalInfoNotify   *GameGlobalInfoNotify   `protobuf:"bytes,2,opt,name=gameGlobalInfoNotify,proto3" json:"gameGlobalInfoNotify,omitempty"`     //玩家加入时对玩家进行同步的所有消息
	Time                   *TimeNotify             `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`                                     //对局时间信息通知
	MapInfo                *MapInfo                `protobuf:"bytes,4,opt,name=mapInfo,proto3" json:"mapInfo,omitempty"`                               //地图信息
	EnterGameNotify        *EnterGameNotify        `protobuf:"bytes,5,opt,name=enterGameNotify,proto3" json:"enterGameNotify,omitempty"`               //进入游戏包
}

func (x *Notify) Reset() {
	*x = Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notify) ProtoMessage() {}

func (x *Notify) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notify.ProtoReflect.Descriptor instead.
func (*Notify) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{0}
}

func (x *Notify) GetEntityInfoChangeNotify() *EntityInfoChangeNotify {
	if x != nil {
		return x.EntityInfoChangeNotify
	}
	return nil
}

func (x *Notify) GetGameGlobalInfoNotify() *GameGlobalInfoNotify {
	if x != nil {
		return x.GameGlobalInfoNotify
	}
	return nil
}

func (x *Notify) GetTime() *TimeNotify {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Notify) GetMapInfo() *MapInfo {
	if x != nil {
		return x.MapInfo
	}
	return nil
}

func (x *Notify) GetEnterGameNotify() *EnterGameNotify {
	if x != nil {
		return x.EnterGameNotify
	}
	return nil
}

type EntityInfoChangeNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityType ENTITY_TYPE `protobuf:"varint,1,opt,name=entityType,proto3,enum=proto.ENTITY_TYPE" json:"entityType,omitempty"` //实体的类型
	EntityId   int64       `protobuf:"varint,2,opt,name=entityId,proto3" json:"entityId,omitempty"`                            //实体的Id
	HeroMsg    *HeroMsg    `protobuf:"bytes,3,opt,name=HeroMsg,proto3" json:"HeroMsg,omitempty"`                               //玩家的信息
	ItemMsg    *ItemMsg    `protobuf:"bytes,4,opt,name=itemMsg,proto3" json:"itemMsg,omitempty"`                               //物体的信息
}

func (x *EntityInfoChangeNotify) Reset() {
	*x = EntityInfoChangeNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityInfoChangeNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityInfoChangeNotify) ProtoMessage() {}

func (x *EntityInfoChangeNotify) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityInfoChangeNotify.ProtoReflect.Descriptor instead.
func (*EntityInfoChangeNotify) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{1}
}

func (x *EntityInfoChangeNotify) GetEntityType() ENTITY_TYPE {
	if x != nil {
		return x.EntityType
	}
	return ENTITY_TYPE_HERO_TYPE
}

func (x *EntityInfoChangeNotify) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityInfoChangeNotify) GetHeroMsg() *HeroMsg {
	if x != nil {
		return x.HeroMsg
	}
	return nil
}

func (x *EntityInfoChangeNotify) GetItemMsg() *ItemMsg {
	if x != nil {
		return x.ItemMsg
	}
	return nil
}

type EnterGameNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId int64 `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"` //玩家ID
	//  HeroMsg HeroMsg = 2; //玩家的信息
	ClientConnectMsg *ConnectMsg `protobuf:"bytes,2,opt,name=clientConnectMsg,proto3" json:"clientConnectMsg,omitempty"` //网络信息
}

func (x *EnterGameNotify) Reset() {
	*x = EnterGameNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterGameNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterGameNotify) ProtoMessage() {}

func (x *EnterGameNotify) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterGameNotify.ProtoReflect.Descriptor instead.
func (*EnterGameNotify) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{2}
}

func (x *EnterGameNotify) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *EnterGameNotify) GetClientConnectMsg() *ConnectMsg {
	if x != nil {
		return x.ClientConnectMsg
	}
	return nil
}

type GameGlobalInfoNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroNumber int32      `protobuf:"varint,1,opt,name=heroNumber,proto3" json:"heroNumber,omitempty"` //玩家数量
	Time       int64      `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`             //游戏对局中的时间(开始时间)
	HeroMsg    []*HeroMsg `protobuf:"bytes,3,rep,name=HeroMsg,proto3" json:"HeroMsg,omitempty"`        //对局中玩家的信息
	ItemMsg    []*ItemMsg `protobuf:"bytes,4,rep,name=ItemMsg,proto3" json:"ItemMsg,omitempty"`        //对局中道具的信息
	MapMsg     *MapMsg    `protobuf:"bytes,5,opt,name=mapMsg,proto3" json:"mapMsg,omitempty"`          //地图信息
}

func (x *GameGlobalInfoNotify) Reset() {
	*x = GameGlobalInfoNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameGlobalInfoNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameGlobalInfoNotify) ProtoMessage() {}

func (x *GameGlobalInfoNotify) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameGlobalInfoNotify.ProtoReflect.Descriptor instead.
func (*GameGlobalInfoNotify) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{3}
}

func (x *GameGlobalInfoNotify) GetHeroNumber() int32 {
	if x != nil {
		return x.HeroNumber
	}
	return 0
}

func (x *GameGlobalInfoNotify) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *GameGlobalInfoNotify) GetHeroMsg() []*HeroMsg {
	if x != nil {
		return x.HeroMsg
	}
	return nil
}

func (x *GameGlobalInfoNotify) GetItemMsg() []*ItemMsg {
	if x != nil {
		return x.ItemMsg
	}
	return nil
}

func (x *GameGlobalInfoNotify) GetMapMsg() *MapMsg {
	if x != nil {
		return x.MapMsg
	}
	return nil
}

type TimeNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time int64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *TimeNotify) Reset() {
	*x = TimeNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeNotify) ProtoMessage() {}

func (x *TimeNotify) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeNotify.ProtoReflect.Descriptor instead.
func (*TimeNotify) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{4}
}

func (x *TimeNotify) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type MapInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapMsg *MapMsg `protobuf:"bytes,1,opt,name=mapMsg,proto3" json:"mapMsg,omitempty"` //地图信息
}

func (x *MapInfo) Reset() {
	*x = MapInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapInfo) ProtoMessage() {}

func (x *MapInfo) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapInfo.ProtoReflect.Descriptor instead.
func (*MapInfo) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{5}
}

func (x *MapInfo) GetMapMsg() *MapMsg {
	if x != nil {
		return x.MapMsg
	}
	return nil
}

var File_notify_proto protoreflect.FileDescriptor

var file_notify_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x6d, 0x73, 0x67, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xc3, 0x02, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x55, 0x0a,
	0x16, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x16, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x12, 0x4f, 0x0a, 0x14, 0x67, 0x61, 0x6d, 0x65, 0x47, 0x6c, 0x6f, 0x62,
	0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x47,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52,
	0x14, 0x67, 0x61, 0x6d, 0x65, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x07,
	0x6d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x6d,
	0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x40, 0x0a, 0x0f, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x47,
	0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d,
	0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x0f, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61,
	0x6d, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x22, 0xbc, 0x01, 0x0a, 0x16, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x12, 0x32, 0x0a, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x0a, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x07, 0x48, 0x65, 0x72, 0x6f, 0x4d, 0x73, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x72,
	0x6f, 0x4d, 0x73, 0x67, 0x52, 0x07, 0x48, 0x65, 0x72, 0x6f, 0x4d, 0x73, 0x67, 0x12, 0x28, 0x0a,
	0x07, 0x69, 0x74, 0x65, 0x6d, 0x4d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x73, 0x67, 0x52, 0x07,
	0x69, 0x74, 0x65, 0x6d, 0x4d, 0x73, 0x67, 0x22, 0x6c, 0x0a, 0x0f, 0x45, 0x6e, 0x74, 0x65, 0x72,
	0x47, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3d, 0x0a, 0x10, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x4d, 0x73, 0x67, 0x52, 0x10, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x4d, 0x73, 0x67, 0x22, 0xc5, 0x01, 0x0a, 0x14, 0x47, 0x61, 0x6d, 0x65, 0x47, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x1e,
	0x0a, 0x0a, 0x68, 0x65, 0x72, 0x6f, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x68, 0x65, 0x72, 0x6f, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x48, 0x65, 0x72, 0x6f, 0x4d, 0x73, 0x67, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x72, 0x6f,
	0x4d, 0x73, 0x67, 0x52, 0x07, 0x48, 0x65, 0x72, 0x6f, 0x4d, 0x73, 0x67, 0x12, 0x28, 0x0a, 0x07,
	0x49, 0x74, 0x65, 0x6d, 0x4d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x73, 0x67, 0x52, 0x07, 0x49,
	0x74, 0x65, 0x6d, 0x4d, 0x73, 0x67, 0x12, 0x25, 0x0a, 0x06, 0x6d, 0x61, 0x70, 0x4d, 0x73, 0x67,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d,
	0x61, 0x70, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x6d, 0x61, 0x70, 0x4d, 0x73, 0x67, 0x22, 0x20, 0x0a,
	0x0a, 0x54, 0x69, 0x6d, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22,
	0x30, 0x0a, 0x07, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x06, 0x6d, 0x61,
	0x70, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x70, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x6d, 0x61, 0x70, 0x4d, 0x73,
	0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notify_proto_rawDescOnce sync.Once
	file_notify_proto_rawDescData = file_notify_proto_rawDesc
)

func file_notify_proto_rawDescGZIP() []byte {
	file_notify_proto_rawDescOnce.Do(func() {
		file_notify_proto_rawDescData = protoimpl.X.CompressGZIP(file_notify_proto_rawDescData)
	})
	return file_notify_proto_rawDescData
}

var file_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_notify_proto_goTypes = []interface{}{
	(*Notify)(nil),                 // 0: proto.Notify
	(*EntityInfoChangeNotify)(nil), // 1: proto.EntityInfoChangeNotify
	(*EnterGameNotify)(nil),        // 2: proto.EnterGameNotify
	(*GameGlobalInfoNotify)(nil),   // 3: proto.GameGlobalInfoNotify
	(*TimeNotify)(nil),             // 4: proto.TimeNotify
	(*MapInfo)(nil),                // 5: proto.MapInfo
	(ENTITY_TYPE)(0),               // 6: proto.ENTITY_TYPE
	(*HeroMsg)(nil),                // 7: proto.HeroMsg
	(*ItemMsg)(nil),                // 8: proto.ItemMsg
	(*ConnectMsg)(nil),             // 9: proto.ConnectMsg
	(*MapMsg)(nil),                 // 10: proto.MapMsg
}
var file_notify_proto_depIdxs = []int32{
	1,  // 0: proto.Notify.entityInfoChangeNotify:type_name -> proto.EntityInfoChangeNotify
	3,  // 1: proto.Notify.gameGlobalInfoNotify:type_name -> proto.GameGlobalInfoNotify
	4,  // 2: proto.Notify.time:type_name -> proto.TimeNotify
	5,  // 3: proto.Notify.mapInfo:type_name -> proto.MapInfo
	2,  // 4: proto.Notify.enterGameNotify:type_name -> proto.EnterGameNotify
	6,  // 5: proto.EntityInfoChangeNotify.entityType:type_name -> proto.ENTITY_TYPE
	7,  // 6: proto.EntityInfoChangeNotify.HeroMsg:type_name -> proto.HeroMsg
	8,  // 7: proto.EntityInfoChangeNotify.itemMsg:type_name -> proto.ItemMsg
	9,  // 8: proto.EnterGameNotify.clientConnectMsg:type_name -> proto.ConnectMsg
	7,  // 9: proto.GameGlobalInfoNotify.HeroMsg:type_name -> proto.HeroMsg
	8,  // 10: proto.GameGlobalInfoNotify.ItemMsg:type_name -> proto.ItemMsg
	10, // 11: proto.GameGlobalInfoNotify.mapMsg:type_name -> proto.MapMsg
	10, // 12: proto.MapInfo.mapMsg:type_name -> proto.MapMsg
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_notify_proto_init() }
func file_notify_proto_init() {
	if File_notify_proto != nil {
		return
	}
	file_msgenum_proto_init()
	file_struct_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_notify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityInfoChangeNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterGameNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameGlobalInfoNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notify_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notify_proto_goTypes,
		DependencyIndexes: file_notify_proto_depIdxs,
		MessageInfos:      file_notify_proto_msgTypes,
	}.Build()
	File_notify_proto = out.File
	file_notify_proto_rawDesc = nil
	file_notify_proto_goTypes = nil
	file_notify_proto_depIdxs = nil
}
